import type { AdminMetrics, Assignment, BankTenant, Course, ProgressRecord, User } from './types'

export const tenants: BankTenant[] = [
  { id: 'acacia', name: 'Acacia Bank', shortName: 'Acacia', initials: 'AB', accent: '#7BC143', dark: '#355B28', tagline: 'Growing capability across every branch' },
  { id: 'highland', name: 'Highland Cooperative Bank', shortName: 'Highland', initials: 'HC', accent: '#D5A52A', dark: '#315648', tagline: 'Practical learning for member-focused banking' },
]

const amlModules = [
  { id: 'aml-1', title: 'Why AML matters', duration: 7, kind: 'lesson' as const, content: ['Money laundering exposes banks to legal, financial, and reputational harm.', 'Every employee contributes by following customer due diligence procedures and raising concerns through the approved channel.'] },
  { id: 'aml-2', title: 'Know your customer', duration: 10, kind: 'lesson' as const, content: ['Customer due diligence confirms who the customer is and why they need the account.', 'Risk profiles must remain current. Update records when ownership, activity, or expected transaction patterns change.'] },
  { id: 'aml-3', title: 'Recognising red flags', duration: 9, kind: 'lesson' as const, content: ['A red flag is a fact or pattern that requires closer review. One unusual transaction does not prove wrongdoing.', 'Examples include unexplained cash activity, rapid movement of funds, and reluctance to provide required information.'] },
  { id: 'aml-4', title: 'Escalation and reporting', duration: 8, kind: 'lesson' as const, content: ['Follow the bank’s internal escalation process promptly and record the facts clearly.', 'Never alert a customer that a suspicious activity report may be considered.'] },
  { id: 'aml-5', title: 'Knowledge check', duration: 6, kind: 'assessment' as const, content: [] },
]

export const courses: Course[] = [
  {
    id: 'aml', title: 'Anti-Money Laundering Annual Refresher', category: 'Compliance', required: true,
    description: 'A practical refresher on customer due diligence, transaction red flags, and internal reporting responsibilities.', audience: 'All employees', languages: ['EN', 'AM'], duration: 40, passMark: 80, certificateAvailable: true,
    objectives: ['Apply customer due diligence requirements', 'Recognise common transaction red flags', 'Use the correct internal escalation process'], modules: amlModules,
    quiz: [
      { id: 'q1', prompt: 'What is the main purpose of customer due diligence?', options: ['To sell more products', 'To understand the customer and account purpose', 'To replace transaction monitoring', 'To approve every customer automatically'], correctIndex: 1, explanation: 'CDD establishes identity, ownership, account purpose, and expected activity.' },
      { id: 'q2', prompt: 'Which situation should receive closer review?', options: ['A customer updates their phone number', 'A salary payment arrives monthly', 'Funds move rapidly through an account with no clear purpose', 'A customer uses mobile banking'], correctIndex: 2, explanation: 'Rapid unexplained movement of funds is a common red flag.' },
      { id: 'q3', prompt: 'What should you do after identifying a possible red flag?', options: ['Ask colleagues informally', 'Tell the customer immediately', 'Follow the bank’s internal escalation process', 'Close the account yourself'], correctIndex: 2, explanation: 'Employees should use the approved internal reporting channel.' },
      { id: 'q4', prompt: 'When should a customer risk profile be updated?', options: ['Only when the account opens', 'When ownership or expected activity changes', 'Only after a regulator asks', 'Never, if identity was verified'], correctIndex: 1, explanation: 'CDD continues throughout the customer relationship.' },
      { id: 'q5', prompt: 'Which statement about suspicious activity is correct?', options: ['One red flag always proves a crime', 'Only managers can notice concerns', 'The customer should be warned first', 'Facts should be recorded clearly and promptly'], correctIndex: 3, explanation: 'Clear and prompt factual records support appropriate investigation.' },
    ],
  },
  { id: 'credit', title: 'Credit Fundamentals', category: 'Credit', required: false, description: 'Build a consistent approach to borrower assessment, cash flow, security, and credit recommendations.', audience: 'Credit and branch teams', languages: ['EN'], duration: 75, passMark: 75, certificateAvailable: true, objectives: ['Assess repayment capacity', 'Identify key credit risks'], modules: [{ id: 'cr-1', title: 'The credit decision', duration: 25, kind: 'lesson', content: ['A sound credit decision starts with repayment capacity and a clear purpose.'] }, { id: 'cr-2', title: 'Cash flow review', duration: 30, kind: 'lesson', content: ['Test the assumptions behind projected cash flow and identify sensitivity to change.'] }, { id: 'cr-3', title: 'Case exercise', duration: 20, kind: 'assessment', content: [] }] },
  { id: 'risk', title: 'Operational Risk Essentials', category: 'Risk', required: true, description: 'Recognise operational risk events and strengthen everyday controls.', audience: 'All employees', languages: ['EN', 'AM'], duration: 35, passMark: 80, certificateAvailable: true, objectives: ['Identify operational risk', 'Report incidents consistently'], modules: [{ id: 'r-1', title: 'Operational risk in practice', duration: 20, kind: 'lesson', content: ['Operational risk can arise from people, processes, systems, or external events.'] }, { id: 'r-2', title: 'Control and reporting', duration: 15, kind: 'lesson', content: ['Prompt reporting helps the bank correct weaknesses and learn from events.'] }] },
  { id: 'service', title: 'Customer Service at the Branch', category: 'Customer Service', required: false, description: 'Handle common branch interactions with clarity, consistency, and care.', audience: 'Branch employees', languages: ['EN', 'AM'], duration: 45, passMark: 70, certificateAvailable: true, objectives: ['Set clear expectations', 'Resolve complaints consistently'], modules: [{ id: 's-1', title: 'A clear customer conversation', duration: 20, kind: 'lesson', content: ['Explain the next step in plain language and confirm that the customer understands.'] }, { id: 's-2', title: 'Complaint scenarios', duration: 25, kind: 'lesson', content: ['Record the complaint accurately and follow the bank’s escalation procedure.'] }] },
  { id: 'cyber', title: 'Digital Banking Security', category: 'Digital Banking', required: true, description: 'Protect customer and bank information from common digital threats.', audience: 'All employees', languages: ['EN'], duration: 30, passMark: 80, certificateAvailable: true, objectives: ['Recognise phishing', 'Protect credentials and devices'], modules: [{ id: 'd-1', title: 'Phishing and social engineering', duration: 15, kind: 'lesson', content: ['Pause when a message creates urgency or asks for credentials.'] }, { id: 'd-2', title: 'Secure daily habits', duration: 15, kind: 'lesson', content: ['Use approved systems and report suspicious messages promptly.'] }] },
  { id: 'onboarding', title: 'New Employee Banking Foundations', category: 'Onboarding', required: false, description: 'An introduction to banking operations, conduct, and customer responsibilities.', audience: 'New employees', languages: ['EN', 'AM'], duration: 90, passMark: 75, certificateAvailable: true, objectives: ['Understand the banking operating model', 'Apply expected standards of conduct'], modules: [{ id: 'o-1', title: 'How a bank works', duration: 45, kind: 'lesson', content: ['Banks connect savers, borrowers, payments, and risk management.'] }, { id: 'o-2', title: 'Your responsibilities', duration: 45, kind: 'lesson', content: ['Bank employees protect customer interests and follow internal controls.'] }] },
  { id: 'acacia-policy', tenantId: 'acacia', title: 'Acacia Customer Complaint Policy', category: 'Customer Service', required: true, description: 'Apply Acacia Bank’s complaint handling and escalation standards.', audience: 'Customer-facing employees', languages: ['EN'], duration: 25, passMark: 80, certificateAvailable: true, objectives: ['Log complaints correctly', 'Meet escalation timelines'], modules: [{ id: 'ap-1', title: 'Policy and service standards', duration: 25, kind: 'lesson', content: ['Every complaint receives a case number, owner, and clear next step.'] }] },
  { id: 'highland-policy', tenantId: 'highland', title: 'Highland Cooperative Lending Policy', category: 'Credit', required: true, description: 'Use Highland’s policy for cooperative and member lending.', audience: 'Credit teams', languages: ['EN', 'AM'], duration: 50, passMark: 80, certificateAvailable: true, objectives: ['Apply eligibility rules', 'Document cooperative ownership'], modules: [{ id: 'hp-1', title: 'Member lending principles', duration: 25, kind: 'lesson', content: ['Confirm membership and the relationship between the member and cooperative.'] }, { id: 'hp-2', title: 'Decision records', duration: 25, kind: 'lesson', content: ['Document the basis for every recommendation and exception.'] }] },
]

export const users: User[] = [
  { id: 'u-ac-1', tenantId: 'acacia', name: 'Hana Tesfaye', staffId: 'ACA-1042', email: 'hana.tesfaye@acacia.demo', portalRole: 'learner', jobTitle: 'Customer Service Officer', grade: 'Officer II', branch: 'Bole Branch', region: 'Addis Ababa', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: 'Today, 09:14' },
  { id: 'u-ac-2', tenantId: 'acacia', name: 'Mekdes Alemu', staffId: 'ACA-2031', email: 'mekdes.alemu@acacia.demo', portalRole: 'learner', jobTitle: 'Branch Manager', grade: 'Manager I', branch: 'Piassa Branch', region: 'Addis Ababa', preferredLanguage: 'Amharic', employmentStatus: 'Active', lastActive: 'Yesterday' },
  { id: 'u-ac-3', tenantId: 'acacia', name: 'Bereket Girma', staffId: 'ACA-3308', email: 'bereket.girma@acacia.demo', portalRole: 'learner', jobTitle: 'Credit Analyst', grade: 'Officer III', branch: 'Hawassa Branch', region: 'Sidama', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: '2 days ago' },
  { id: 'u-ac-4', tenantId: 'acacia', name: 'Selamawit Kebede', staffId: 'ACA-4064', email: 'selamawit.kebede@acacia.demo', portalRole: 'learner', jobTitle: 'Teller', grade: 'Officer I', branch: 'Bahir Dar Branch', region: 'Amhara', preferredLanguage: 'Amharic', employmentStatus: 'Active', lastActive: '5 days ago' },
  { id: 'a-ac-1', tenantId: 'acacia', name: 'Samuel Abebe', staffId: 'ACA-HR-12', email: 'samuel.abebe@acacia.demo', portalRole: 'admin', jobTitle: 'Learning and Development Manager', grade: 'Manager II', branch: 'Head Office', region: 'Addis Ababa', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: 'Today' },
  { id: 'u-hi-1', tenantId: 'highland', name: 'Dawit Bekele', staffId: 'HCB-1188', email: 'dawit.bekele@highland.demo', portalRole: 'learner', jobTitle: 'Credit Analyst', grade: 'Officer II', branch: 'Hawassa Branch', region: 'Sidama', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: 'Today, 08:40' },
  { id: 'u-hi-2', tenantId: 'highland', name: 'Rahel Tadesse', staffId: 'HCB-2204', email: 'rahel.tadesse@highland.demo', portalRole: 'learner', jobTitle: 'Cooperative Banking Officer', grade: 'Officer III', branch: 'Adama Branch', region: 'Oromia', preferredLanguage: 'Amharic', employmentStatus: 'Active', lastActive: 'Yesterday' },
  { id: 'u-hi-3', tenantId: 'highland', name: 'Yonas Kassa', staffId: 'HCB-3190', email: 'yonas.kassa@highland.demo', portalRole: 'learner', jobTitle: 'Branch Manager', grade: 'Manager I', branch: 'Mekelle Branch', region: 'Tigray', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: '3 days ago' },
  { id: 'u-hi-4', tenantId: 'highland', name: 'Liya Mulugeta', staffId: 'HCB-4027', email: 'liya.mulugeta@highland.demo', portalRole: 'learner', jobTitle: 'Teller', grade: 'Officer I', branch: 'Jimma Branch', region: 'Oromia', preferredLanguage: 'Amharic', employmentStatus: 'Active', lastActive: '8 days ago' },
  { id: 'a-hi-1', tenantId: 'highland', name: 'Sara Desta', staffId: 'HCB-HR-09', email: 'sara.desta@highland.demo', portalRole: 'admin', jobTitle: 'Head of People Development', grade: 'Director', branch: 'Head Office', region: 'Addis Ababa', preferredLanguage: 'English', employmentStatus: 'Active', lastActive: 'Today' },
]

export const initialAssignments: Assignment[] = [
  { id: 'as-ac-1', tenantId: 'acacia', courseId: 'aml', title: '2026 AML Refresher', required: true, dueDate: '2026-10-15', audienceType: 'Everyone', matchedEmployees: 2480 },
  { id: 'as-ac-2', tenantId: 'acacia', courseId: 'risk', title: 'Operational Risk Essentials', required: true, dueDate: '2026-11-01', audienceType: 'Everyone', matchedEmployees: 2480 },
  { id: 'as-ac-3', tenantId: 'acacia', courseId: 'acacia-policy', title: 'Complaint Policy Update', required: true, dueDate: '2026-10-01', audienceType: 'Role', audienceValue: 'Customer Service Officer', matchedEmployees: 426 },
  { id: 'as-hi-1', tenantId: 'highland', courseId: 'aml', title: '2026 AML Refresher', required: true, dueDate: '2026-10-20', audienceType: 'Everyone', matchedEmployees: 1870 },
  { id: 'as-hi-2', tenantId: 'highland', courseId: 'highland-policy', title: 'Cooperative Lending Policy', required: true, dueDate: '2026-10-30', audienceType: 'Role', audienceValue: 'Credit Analyst', matchedEmployees: 318 },
]

export const initialProgress: ProgressRecord[] = [
  { tenantId: 'acacia', userId: 'u-ac-1', courseId: 'aml', percent: 60, completedModuleIds: ['aml-1', 'aml-2', 'aml-3'], attempts: 0, status: 'In progress' },
  { tenantId: 'acacia', userId: 'u-ac-1', courseId: 'risk', percent: 0, completedModuleIds: [], attempts: 0, status: 'Not started' },
  { tenantId: 'acacia', userId: 'u-ac-1', courseId: 'acacia-policy', percent: 100, completedModuleIds: ['ap-1'], score: 90, attempts: 1, status: 'Completed' },
  { tenantId: 'highland', userId: 'u-hi-1', courseId: 'aml', percent: 40, completedModuleIds: ['aml-1', 'aml-2'], attempts: 0, status: 'In progress' },
  { tenantId: 'highland', userId: 'u-hi-1', courseId: 'highland-policy', percent: 0, completedModuleIds: [], attempts: 0, status: 'Not started' },
]

export const metrics: AdminMetrics[] = [
  { tenantId: 'acacia', assignedEmployees: 2480, completionRate: 72, overdue: 184, averageScore: 84, trend: [{ month: 'Apr', completion: 41 }, { month: 'May', completion: 48 }, { month: 'Jun', completion: 55 }, { month: 'Jul', completion: 61 }, { month: 'Aug', completion: 66 }, { month: 'Sep', completion: 72 }], regions: [{ name: 'Addis Ababa', completion: 81 }, { name: 'Sidama', completion: 74 }, { name: 'Oromia', completion: 69 }, { name: 'Amhara', completion: 63 }] },
  { tenantId: 'highland', assignedEmployees: 1870, completionRate: 64, overdue: 231, averageScore: 79, trend: [{ month: 'Apr', completion: 32 }, { month: 'May', completion: 38 }, { month: 'Jun', completion: 44 }, { month: 'Jul', completion: 51 }, { month: 'Aug', completion: 58 }, { month: 'Sep', completion: 64 }], regions: [{ name: 'Sidama', completion: 72 }, { name: 'Oromia', completion: 68 }, { name: 'Addis Ababa', completion: 64 }, { name: 'Tigray', completion: 55 }] },
]

export const getTenantCourses = (tenantId: string) => courses.filter((course) => !course.tenantId || course.tenantId === tenantId)
